# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JSONitor.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.filepathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filepathLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.filepathLineEdit.setObjectName("filepathLineEdit")
        self.gridLayout.addWidget(self.filepathLineEdit, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGo = QtWidgets.QMenu(self.menubar)
        self.menuGo.setObjectName("menuGo")
        self.menuGo_to_Tab = QtWidgets.QMenu(self.menuGo)
        self.menuGo_to_Tab.setObjectName("menuGo_to_Tab")
        self.menuSet_Bookmark = QtWidgets.QMenu(self.menuGo)
        self.menuSet_Bookmark.setObjectName("menuSet_Bookmark")
        self.menuGo_Bookmark = QtWidgets.QMenu(self.menuGo)
        self.menuGo_Bookmark.setObjectName("menuGo_Bookmark")
        self.menuJSON = QtWidgets.QMenu(self.menubar)
        self.menuJSON.setObjectName("menuJSON")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReopen_Tab = QtWidgets.QAction(MainWindow)
        self.actionReopen_Tab.setObjectName("actionReopen_Tab")
        self.actionCycle_Tabs = QtWidgets.QAction(MainWindow)
        self.actionCycle_Tabs.setObjectName("actionCycle_Tabs")
        self.actionPrevious_Tab = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Tab.setObjectName("actionPrevious_Tab")
        self.actionNext_Tab = QtWidgets.QAction(MainWindow)
        self.actionNext_Tab.setObjectName("actionNext_Tab")
        self.actionSelect_Word = QtWidgets.QAction(MainWindow)
        self.actionSelect_Word.setObjectName("actionSelect_Word")
        self.actionGo_to_Tab_1 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_1.setObjectName("actionGo_to_Tab_1")
        self.actionGo_to_Tab_2 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_2.setObjectName("actionGo_to_Tab_2")
        self.actionGo_to_Tab_3 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_3.setObjectName("actionGo_to_Tab_3")
        self.actionGo_to_Tab_4 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_4.setVisible(True)
        self.actionGo_to_Tab_4.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionGo_to_Tab_4.setIconVisibleInMenu(True)
        self.actionGo_to_Tab_4.setObjectName("actionGo_to_Tab_4")
        self.actionGo_to_Tab_5 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_5.setObjectName("actionGo_to_Tab_5")
        self.actionGo_to_Tab_6 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_6.setObjectName("actionGo_to_Tab_6")
        self.actionGo_to_Tab_7 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_7.setObjectName("actionGo_to_Tab_7")
        self.actionGo_to_Tab_8 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_8.setObjectName("actionGo_to_Tab_8")
        self.actionGo_to_Tab_9 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_9.setObjectName("actionGo_to_Tab_9")
        self.actionGo_to_Tab_10 = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Tab_10.setObjectName("actionGo_to_Tab_10")
        self.actiontemp = QtWidgets.QAction(MainWindow)
        self.actiontemp.setObjectName("actiontemp")
        self.actionasdf = QtWidgets.QAction(MainWindow)
        self.actionasdf.setObjectName("actionasdf")
        self.actiontemp_2 = QtWidgets.QAction(MainWindow)
        self.actiontemp_2.setObjectName("actiontemp_2")
        self.actiontemp_3 = QtWidgets.QAction(MainWindow)
        self.actiontemp_3.setObjectName("actiontemp_3")
        self.actionGo_to_Line = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Line.setObjectName("actionGo_to_Line")
        self.actionUpdate_Text = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Text.setObjectName("actionUpdate_Text")
        self.actionUpdate_Tree_View = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Tree_View.setObjectName("actionUpdate_Tree_View")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_All = QtWidgets.QAction(MainWindow)
        self.actionFind_All.setObjectName("actionFind_All")
        self.actionSet_Focus_To_Text_View = QtWidgets.QAction(MainWindow)
        self.actionSet_Focus_To_Text_View.setObjectName("actionSet_Focus_To_Text_View")
        self.actionSet_Focus_To_Tree_View = QtWidgets.QAction(MainWindow)
        self.actionSet_Focus_To_Tree_View.setObjectName("actionSet_Focus_To_Tree_View")
        self.actionReset_Settings = QtWidgets.QAction(MainWindow)
        self.actionReset_Settings.setObjectName("actionReset_Settings")
        self.actionCopy_Text = QtWidgets.QAction(MainWindow)
        self.actionCopy_Text.setObjectName("actionCopy_Text")
        self.actionPretty_Print_Text = QtWidgets.QAction(MainWindow)
        self.actionPretty_Print_Text.setObjectName("actionPretty_Print_Text")
        self.actionCompact_Text = QtWidgets.QAction(MainWindow)
        self.actionCompact_Text.setObjectName("actionCompact_Text")
        self.actionSort_Text_Alphabetically = QtWidgets.QAction(MainWindow)
        self.actionSort_Text_Alphabetically.setObjectName("actionSort_Text_Alphabetically")
        self.actionSave_All = QtWidgets.QAction(MainWindow)
        self.actionSave_All.setObjectName("actionSave_All")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionReopen_Tab)
        self.menuFile.addAction(self.actionCycle_Tabs)
        self.menuFile.addAction(self.actionPrevious_Tab)
        self.menuFile.addAction(self.actionNext_Tab)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionReset_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy_Text)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFind_All)
        self.menuHelp.addAction(self.actionAbout)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_1)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_2)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_3)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_4)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_5)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_6)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_7)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_8)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_9)
        self.menuGo_to_Tab.addAction(self.actionGo_to_Tab_10)
        self.menuGo.addAction(self.menuGo_to_Tab.menuAction())
        self.menuGo.addSeparator()
        self.menuGo.addAction(self.menuSet_Bookmark.menuAction())
        self.menuGo.addAction(self.menuGo_Bookmark.menuAction())
        self.menuGo.addSeparator()
        self.menuGo.addAction(self.actionGo_to_Line)
        self.menuGo.addSeparator()
        self.menuGo.addAction(self.actionSet_Focus_To_Text_View)
        self.menuGo.addAction(self.actionSet_Focus_To_Tree_View)
        self.menuJSON.addAction(self.actionUpdate_Text)
        self.menuJSON.addAction(self.actionUpdate_Tree_View)
        self.menuJSON.addSeparator()
        self.menuJSON.addAction(self.actionPretty_Print_Text)
        self.menuJSON.addAction(self.actionCompact_Text)
        self.menuJSON.addSeparator()
        self.menuJSON.addAction(self.actionSort_Text_Alphabetically)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuJSON.menuAction())
        self.menubar.addAction(self.menuGo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JSONitor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuGo.setTitle(_translate("MainWindow", "Go"))
        self.menuGo_to_Tab.setTitle(_translate("MainWindow", "Go to Tab"))
        self.menuSet_Bookmark.setTitle(_translate("MainWindow", "Set Bookmark"))
        self.menuGo_Bookmark.setTitle(_translate("MainWindow", "Go to Bookmark"))
        self.menuJSON.setTitle(_translate("MainWindow", "JSON"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionUndo.setText(_translate("MainWindow", "Undo Special"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo Special"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Y"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionClose.setText(_translate("MainWindow", "Close Tab"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReopen_Tab.setText(_translate("MainWindow", "Reopen Tab"))
        self.actionReopen_Tab.setShortcut(_translate("MainWindow", "Ctrl+Shift+T"))
        self.actionCycle_Tabs.setText(_translate("MainWindow", "Cycle Tabs"))
        self.actionCycle_Tabs.setShortcut(_translate("MainWindow", "Ctrl+Tab"))
        self.actionPrevious_Tab.setText(_translate("MainWindow", "Previous Tab"))
        self.actionPrevious_Tab.setShortcut(_translate("MainWindow", "Ctrl+PgUp"))
        self.actionNext_Tab.setText(_translate("MainWindow", "Next Tab"))
        self.actionNext_Tab.setShortcut(_translate("MainWindow", "Ctrl+PgDown"))
        self.actionSelect_Word.setText(_translate("MainWindow", "Select Word"))
        self.actionSelect_Word.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionGo_to_Tab_1.setText(_translate("MainWindow", "Go to Tab 1"))
        self.actionGo_to_Tab_1.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionGo_to_Tab_2.setText(_translate("MainWindow", "Go to Tab 2"))
        self.actionGo_to_Tab_2.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionGo_to_Tab_3.setText(_translate("MainWindow", "Go to Tab 3"))
        self.actionGo_to_Tab_3.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionGo_to_Tab_4.setText(_translate("MainWindow", "Go to Tab 4"))
        self.actionGo_to_Tab_4.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.actionGo_to_Tab_5.setText(_translate("MainWindow", "Go to Tab 5"))
        self.actionGo_to_Tab_5.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.actionGo_to_Tab_6.setText(_translate("MainWindow", "Go to Tab 6"))
        self.actionGo_to_Tab_6.setShortcut(_translate("MainWindow", "Ctrl+6"))
        self.actionGo_to_Tab_7.setText(_translate("MainWindow", "Go to Tab 7"))
        self.actionGo_to_Tab_7.setShortcut(_translate("MainWindow", "Ctrl+7"))
        self.actionGo_to_Tab_8.setText(_translate("MainWindow", "Go to Tab 8"))
        self.actionGo_to_Tab_8.setShortcut(_translate("MainWindow", "Ctrl+8"))
        self.actionGo_to_Tab_9.setText(_translate("MainWindow", "Go to Tab 9"))
        self.actionGo_to_Tab_9.setShortcut(_translate("MainWindow", "Ctrl+9"))
        self.actionGo_to_Tab_10.setText(_translate("MainWindow", "Go to Tab 10"))
        self.actionGo_to_Tab_10.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.actiontemp.setText(_translate("MainWindow", "temp"))
        self.actionasdf.setText(_translate("MainWindow", "asdf"))
        self.actiontemp_2.setText(_translate("MainWindow", "temp"))
        self.actiontemp_3.setText(_translate("MainWindow", "temp"))
        self.actionGo_to_Line.setText(_translate("MainWindow", "Go to Line"))
        self.actionGo_to_Line.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionUpdate_Text.setText(_translate("MainWindow", "Update Text"))
        self.actionUpdate_Text.setToolTip(_translate("MainWindow", "Update Text based upon Tree View"))
        self.actionUpdate_Text.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionUpdate_Tree_View.setText(_translate("MainWindow", "Update Tree View"))
        self.actionUpdate_Tree_View.setToolTip(_translate("MainWindow", "Update Tree View based upon Text"))
        self.actionUpdate_Tree_View.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionFind_All.setText(_translate("MainWindow", "Find All"))
        self.actionFind_All.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionSet_Focus_To_Text_View.setText(_translate("MainWindow", "Set Focus To Text View"))
        self.actionSet_Focus_To_Text_View.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.actionSet_Focus_To_Tree_View.setText(_translate("MainWindow", "Set Focus To Tree View"))
        self.actionSet_Focus_To_Tree_View.setShortcut(_translate("MainWindow", "Ctrl+Shift+Return"))
        self.actionReset_Settings.setText(_translate("MainWindow", "Reset Settings"))
        self.actionCopy_Text.setText(_translate("MainWindow", "Copy Text"))
        self.actionCopy_Text.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPretty_Print_Text.setText(_translate("MainWindow", "Pretty Print Text"))
        self.actionCompact_Text.setText(_translate("MainWindow", "Compact Text"))
        self.actionSort_Text_Alphabetically.setText(_translate("MainWindow", "Sort Text Alphabetically"))
        self.actionSave_All.setText(_translate("MainWindow", "Save All"))
        self.actionSave_All.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))

